### ISSUE TITLE
Bei "Unser Angebot" neigt man dazu, den grauen Erklärtext zu überlesen.

### ISSUE THREAD

**Issue by spilot** [d120/kif-sponsoring-website#2]
Man könnte z.B. den Preis unter den grauen Text schreiben, den grauen Text größer machen, ihn in einer anderen Farbe präsentieren....

**Comment by jlauinger** [comment]
Preis unter die Beschreibung könnte gehen, Farbe ist halt schwierig weil ich eigentlich nicht noch eine zusätzliche Farbe hinzufügen möchte
